### ISSUE TITLE
Front End track courses to be completed

### ISSUE THREAD

**Issue by eternale88** [eternale88/treehouse_practice#2]
## TODO

*Courses completed and those left to complete Code Louisville's Treehouse Front End Development track*
* [x] Console Foundations
* [x] HTML Forms
* [x] CSS Layout Basics
* [x] JavaScript, Loops, Arrays and Objects
* [x] CSS Selectors
* [x] jQuery Basics
* [x] CSS Flexbox Layout
* [x] HTML Tables
* [x] Interactive Webpages with JavaScript
* [x] Git Basics
* [ ] Github Basics 
* [ ] HTML Video and Audio
* [ ] Responsive Layouts
* [ ] Ajax Basics
* [ ] Object-Oriented JavaScript
* [ ] Accessibility
* [ ] Website Optimization
* [ ] Front End Performance Optimization
* [ ] Introduction to Design Patterns
* [ ] Framework Basics

💯  :sailboat: ✈️ : :rocket:
